import os
from io import BytesIO
from openpyxl import Workbook
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

def generate_excel_report(data: dict) -> str:
    """
    Generates a multi-sheet Excel report resembling the L&T BRSR format.
    Returns the file path.
    """
    wb = Workbook()
    
    # --- Sheet 1: Cover ---
    ws_cover = wb.active
    ws_cover.title = "Cover"
    ws_cover.append(["BUSINESS RESPONSIBILITY & SUSTAINABILITY REPORT"])
    ws_cover.append([])
    ws_cover.append(["Generated by", "ESGraph Portal"])
    ws_cover.append(["Reporting Boundary", "Consolidated (Demo)"])
    ws_cover.append([])
    ws_cover.append(["* Synthetic Demo Data *"])

    # --- Sheet 2: Section A & B (Corporate Info) ---
    ws_corp = wb.create_sheet(title="Section A & B")
    ws_corp.append(["Section A & B: General & Management Disclosures"])
    ws_corp.append(["Indicator", "Sub Key", "Value"])
    for key in ["CYBER_INCIDENTS", "ACCOUNTS_PAYABLE", "CONCENTRATION", "RELATED_PARTY", "VALUE_CHAIN_ASSESSED"]:
        if key in data:
            for sub_key, val in data[key].items():
                ws_corp.append([key, sub_key, val])

    # --- Sheet 3: Principle 3 (Well-being & Safety) ---
    ws_p3 = wb.create_sheet(title="Principle 3 (Safety)")
    ws_p3.append(["Principle 3: Employee Well-being & Safety"])
    ws_p3.append(["Indicator", "Sub Key", "Value"])
    for key in ["WORKFORCE", "SAFETY_LTIFR", "SAFETY_INCIDENTS", "WELLBEING_SPEND"]:
        if key in data:
            for sub_key, val in data[key].items():
                ws_p3.append([key, sub_key, val])

    # --- Sheet 4: Principle 6 (Environment) ---
    ws_p6 = wb.create_sheet(title="Principle 6 (Environment)")
    ws_p6.append(["Principle 6: Environmental Performance"])
    ws_p6.append(["Indicator", "Sub Key", "Value"])
    for key in ["GHG_S1", "GHG_S2", "WATER_WITHDRAWAL", "WATER_DISCHARGE", "ENERGY_CONS", "WASTE_GEN", "WASTE_REC", "WASTE_DISP"]:
        if key in data:
            for sub_key, val in data[key].items():
                ws_p6.append([key, sub_key, val])

    # --- Sheet 5: Principles 5, 8, 9 (Social & Openness) ---
    ws_social = wb.create_sheet(title="Principles 5, 8, 9")
    ws_social.append(["Principles 5, 8, 9: Social, Inclusive Development, Consumers"])
    ws_social.append(["Indicator", "Sub Key", "Value"])
    for key in ["WAGES_GENDER", "POSH_COMPLAINTS", "PROCUREMENT_MSME", "JOB_CREATION"]:
        if key in data:
            for sub_key, val in data[key].items():
                ws_social.append([key, sub_key, val])

    # --- Sheet 6: BRSR Core Summary ---
    ws_core = wb.create_sheet(title="BRSR Core Summary")
    ws_core.append(["BRSR Core KPIs (Subject to Assurance)"])
    ws_core.append(["Indicator Code", "Total Value"])
    for key, values in data.items():
        if isinstance(values, dict):
            # Sum up total for summary
            total = sum(values.values())
            ws_core.append([key, total])
        else:
            ws_core.append([key, values])

    # Save to disk
    os.makedirs("exports", exist_ok=True)
    filepath = os.path.join("exports", "brsr_report.xlsx")
    wb.save(filepath)
    return filepath

def generate_pdf_report(data: dict) -> str:
    """
    Generates a basic PDF report and saves it to a temp file.
    Returns the file path.
    """
    os.makedirs("exports", exist_ok=True)
    filepath = os.path.join("exports", "brsr_report.pdf")
    
    c = canvas.Canvas(filepath, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 750, "BRSR Consolidated ESG Report")
    
    c.setFont("Helvetica", 12)
    y = 700
    
    for key, value in data.items():
        text = f"{key}: {value}"
        c.drawString(50, y, text[:100]) # truncate for safety in demo
        y -= 20
        if y < 100:
            c.showPage()
            y = 750
            
    # Watermark
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(250, 50, "* Synthetic Demo Data *")
    
    c.save()
    return filepath
